/**
 * PRISMA 2020 Systematic Review & Meta-Synthesis Exporter
 * Formats Veridex evidence matrix into a formal, publication-ready PRISMA Markdown & JSON document.
 */

export function generatePrismaMarkdownReport(matrixData) {
  const {
    research_query = 'Scientific Literature Review',
    aggregate = {},
    narrative = '',
    papers = [],
    extractions = [],
    contradictions = [],
  } = matrixData;

  const timestamp = new Date().toISOString().split('T')[0];
  const total = aggregate.total_studies || extractions.length || 0;
  const pos = aggregate.positive_count || 0;
  const neg = aggregate.negative_count || 0;
  const neutral = aggregate.neutral_or_mixed_count || 0;
  const tier = aggregate.confidence_tier || 'MODERATE';
  const resolved = aggregate.resolved_contradictions || 0;
  const open = aggregate.open_contradictions || 0;

  // Build Study Matrix Table
  const tableRows = extractions.map((ext, idx) => {
    const p = papers.find((paper) => paper.id === ext.paper_id) || {};
    const title = (p.title || ext.paper_title || `Study ${idx + 1}`).replace(/\|/g, '-');
    const journal = p.journal || ext.journal || 'Peer-Reviewed Journal';
    const year = p.year || ext.paper_year || 'N/A';
    const n = ext.sample_size || 'N/A';
    const model = (ext.model_system || 'N/A').replace(/\|/g, '-');
    const dir = ext.effect_direction || 'NEUTRAL';
    const pVal = ext.p_value !== null && ext.p_value !== undefined ? `p=${ext.p_value}` : 'N/A';
    const bias = ext.risk_of_bias || 'MODERATE';

    return `| ${idx + 1} | **${title}** | ${journal} (${year}) | ${n} | ${model} | \`${dir}\` | ${pVal} | ${bias} |`;
  }).join('\n');

  // Build Contradiction Ledger
  const contradictionRows = contradictions.length > 0
    ? contradictions.map((c, idx) => {
        const pA = papers.find((p) => p.id === c.paper_a_id) || {};
        const pB = papers.find((p) => p.id === c.paper_b_id) || {};
        const titleA = pA.title || c.paper_a_title || 'Study A';
        const titleB = pB.title || c.paper_b_title || 'Study B';
        const icon = c.status === 'RESOLVED' ? '🟢 RESOLVED' : '🟠 IRRECONCILABLE';
        const confounder = c.isolated_confounder ? `**Isolated Confounder**: *${c.isolated_confounder}*` : 'No explicit methodological difference stated.';

        return `### Dispute ${idx + 1}: ${icon}\n- **Study A (+)**: ${titleA}\n- **Study B (-)**: ${titleB}\n- **Conflict**: ${c.conflict_summary}\n- ${confounder}\n`;
      }).join('\n')
    : '_No pairwise contradictions identified within this evidence corpus._\n';

  return `
# PRISMA 2020 Systematic Review & Evidence Consensus Report

> **Target Research Question**: "${research_query}"  
> **Generated by**: Veridex Autonomous Multi-Agent Consensus Engine  
> **Date**: ${timestamp} | **Evidence Certainty Grade**: **[${tier}]**

---

## 1. Executive Meta-Synthesis

${narrative}

---

## 2. PRISMA 2020 Evidence Flow & Metrics

\`\`\`text
┌────────────────────────────────────────────────────────┐
│ 1. IDENTIFICATION                                      │
│    • Studies Vector-Indexed in CockroachDB: ${total}       │
└───────────────────────────┬────────────────────────────┘
                            │
                            ▼
┌────────────────────────────────────────────────────────┐
│ 2. METHODOLOGICAL EXTRACTION                           │
│    • Parametric Extractions Analyzed: ${extractions.length}           │
│    • Statistically Significant (p < 0.05): ${aggregate.significant_count || 'N/A'}/${total}  │
│    • Risk of Bias: ${aggregate.risk_of_bias_breakdown?.LOW || 0} Low | ${aggregate.risk_of_bias_breakdown?.MODERATE || 0} Moderate | ${aggregate.risk_of_bias_breakdown?.HIGH || 0} High   │
└───────────────────────────┬────────────────────────────┘
                            │
                            ▼
┌────────────────────────────────────────────────────────┐
│ 3. CONFLICT ARBITRATION & SYNTHESIS                    │
│    • Direction: ${pos} Positive | ${neg} Negative | ${neutral} Neutral │
│    • Contradiction Pairs Arbitrated: ${resolved + open} (${resolved} Resolved, ${open} Open)│
│    • Final Confidence Tier: ${tier}                     │
└────────────────────────────────────────────────────────┘
\`\`\`

---

## 3. Systematic Study Characteristics Matrix

| # | Study Title | Source & Year | Sample Size (N) | Model System | Direction | p-value | Risk of Bias |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
${tableRows}

---

## 4. Methodological Contradiction & Confounder Ledger

${contradictionRows}

---

## 5. Methodological Notes & Zero-Hallucination Audit Trail
- **Extraction Agent**: Deterministic extraction with verbatim citation enforcement.
- **Arbiter Agent**: Adversarial pairwise comparison isolating dosage, model system, and confounding variables.
- **Statistical Aggregation**: Pure deterministic computation with zero LLM arithmetic.
- **Persistent Storage**: CockroachDB distributed vector index (C-SPANN) with AWS Bedrock Titan V2 embeddings.

---
*Report generated automatically by Veridex under the MIT License.*
`.trim();
}
